/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#10131a',
        'surface-dim': '#10131a',
        'surface-bright': '#363940',
        'surface-container-lowest': '#0b0e14',
        'surface-container-low': '#191c22',
        'surface-container': '#1d2026',
        'surface-container-high': '#272a31',
        'surface-container-highest': '#32353c',
        'on-surface': '#e1e2eb',
        'on-surface-variant': '#e4bebc',
        'inverse-surface': '#e1e2eb',
        'inverse-on-surface': '#2e3037',
        outline: '#ab8987',
        'outline-variant': '#5b403f',
        primary: '#ffb3b1',
        'on-primary': '#680011',
        'primary-container': '#ff535b',
        'on-primary-container': '#5b000e',
        'inverse-primary': '#bb152c',
        secondary: '#e9c349',
        'on-secondary': '#3c2f00',
        'secondary-container': '#af8d11',
        'on-secondary-container': '#342800',
        tertiary: '#6fd8c8',
        'on-tertiary': '#003731',
        'tertiary-container': '#30a193',
        'on-tertiary-container': '#00302a',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#10131a',
        'on-background': '#e1e2eb',
        'surface-variant': '#32353c',
        // brand accent names referenced in the spec prose
        crimson: '#E63946',
        'crimson-dark': '#9B2226',
        gold: '#D4AF37',
        teal: '#2A9D8F',
        obsidian: '#0B0E14',
        slate: '#161B22',
      },
      fontFamily: {
        display: ['var(--font-display)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', fontWeight: '700', letterSpacing: '0.1em' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
      },
      backgroundImage: {
        'crimson-gradient': 'linear-gradient(to bottom, #E63946, #9B2226)',
        'scrim-bottom': 'linear-gradient(to top, rgba(0,0,0,0.85), transparent)',
      },
      boxShadow: {
        glow: '0px 4px 20px rgba(230, 57, 70, 0.3)',
        'glow-lg': '0px 20px 60px rgba(230, 57, 70, 0.45)',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      maxWidth: {
        content: '1400px',
      },
      backdropBlur: {
        modal: '20px',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 32s linear infinite',
      },
    },
  },
  plugins: [],
};
